name: twenty

services:
  change-vol-ownership:
    extends:
      file: docker-compose.local.yml
      service: change-vol-ownership

  server:
    extends:
      file: docker-compose.local.yml
      service: server

  worker:
    extends:
      file: docker-compose.local.yml
      service: worker

  db:
    extends:
      file: docker-compose.local.yml
      service: db
    ports:
      - "5432:5432"
    image: twentycrm/twenty-postgres-spilo:${TAG:-latest}

  redis:
    extends:
      file: docker-compose.local.yml
      service: redis
    ports:
      - "6379:6379"

volumes:
  docker-data:
  db-data:
  server-local-data:
