name: twenty

services:
  change-vol-ownership:
    extends:
      file: docker-compose.yml
      service: change-vol-ownership

  server:
    extends:
      file: docker-compose.yml
      service: server
    # volumes_from and depends_on are never shared between services using extends
    # https://docs.docker.com/compose/how-tos/multiple-compose-files/extends/#exceptions-and-limitations
    depends_on:
      change-vol-ownership:
        condition: service_completed_successfully
      db:
        condition: service_healthy

  worker:
    extends:
      file: docker-compose.yml
      service: worker
    # depends_on is not shared between services using extends
    depends_on:
      db:
        condition: service_healthy
      server:
        condition: service_healthy

  db:
    extends:
      file: docker-compose.yml
      service: db
    ports:
      - "5432:5432"

  redis:
    extends:
      file: docker-compose.yml
      service: redis
    ports:
      - "6379:6379"

volumes:
  docker-data:
  db-data:
  server-local-data:
