name: twenty

services:
  change-vol-ownership:
    extends:
      file: docker-compose.yml
      service: change-vol-ownership

  server:
    extends:
      file: docker-compose.yml
      service: server
    image: twentycrm/twenty:${TAG:-latest}
    # volumes_from and depends_on are never shared between services using extends
    # https://docs.docker.com/compose/how-tos/multiple-compose-files/extends/#exceptions-and-limitations
    depends_on:
      change-vol-ownership:
        condition: service_completed_successfully
      db:
        condition: service_healthy

  worker:
    extends:
      file: docker-compose.yml
      service: worker
    image: twentycrm/twenty:${TAG:-latest}
    # depends_on is not shared between services using extends
    depends_on:
      db:
        condition: service_healthy
      server:
        condition: service_healthy

  db:
    extends:
      file: docker-compose.yml
      service: db
    image: twentycrm/twenty-postgres-spilo:${TAG:-latest}

  redis:
    extends:
      file: docker-compose.yml
      service: redis

volumes:
  docker-data:
  db-data:
  server-local-data:
