name: twenty

services:
  change-vol-ownership:
    extends:
      file: docker-compose.yml
      service: change-vol-ownership

  server:
    extends:
      file: docker-compose.yml
      service: server
    environment:
      # === additional environment variables ===
      IS_MULTIWORKSPACE_ENABLED: true
      DEBUG_MODE: true
      SIGN_IN_PREFILLED: true

  worker:
    extends:
      file: docker-compose.yml
      service: worker

  db:
    extends:
      file: docker-compose.yml
      service: db
    ports:
      - "5432:5432"

  redis:
    extends:
      file: docker-compose.yml
      service: redis
    ports:
      - "6379:6379"

volumes:
  docker-data:
  db-data:
  server-local-data:
